# Generated by Django 3.2.3 on 2021-07-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='status_medico',
        ),
        migrations.RemoveField(
            model_name='postodetrabalho',
            name='status_posto',
        ),
    ]
