# Generated by Django 3.2.3 on 2021-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210708_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabeladeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_posto', models.CharField(max_length=55)),
                ('data_de_trabalho', models.DateField()),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=30)),
            ],
        ),
    ]
