# Generated by Django 3.2.3 on 2021-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tabeladehorario_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('data_de_trabalho', models.DateField()),
            ],
        ),
    ]
